// Descripciones del tarifador: campos de formulario.

import type { HintMap } from '../../../components/base/hintKey';

export const CAMPOS: HintMap = {
  'Código': 'Identificador corto y único. No se puede repetir.',
  'Nombre': 'Nombre con el que se muestra.',
  'Nombre visible': 'Nombre con el que se muestra en las pantallas.',
  'Alcance': 'Dónde aplica: todo el país o una sola compañía.',
  'Compañía': 'Transportista al que pertenece.',
  'Compañía opcional': 'Si se elige, solo aplica a esa compañía.',
  'País': 'País al que aplica.',
  'Etapa del cálculo': 'Momento en que se aplica: base, variable, recargo, ajuste o impuesto.',
  'Etapa base': 'Etapa del cálculo de la que se toma el subtotal.',
  'Se suma o compite': 'Si suma con las demás reglas o compite con otras: solo gana una.',
  'Grupo con el que compite': 'Las reglas del mismo grupo compiten entre sí; gana una.',
  'Prioridad menor gana': 'Cuando hay empate, gana el número más bajo.',
  'Rige desde': 'Primer día en que la regla vale.',
  'Rige hasta': 'Último día en que la regla vale. Vacío = sin vencimiento.',
  'Aplica cuando': 'Condición que debe cumplir el viaje para que la regla aplique.',
  'Operador': 'Cómo se calcula: monto fijo, por unidad, por bloque, porcentaje, tramos o tarifario.',
  'Variable': 'Dato del viaje que se usa en el cálculo.',
  'Importe': 'Monto de la regla, siempre positivo. El efecto decide si suma o resta.',
  'Efecto': 'Si el importe suma o resta al total.',
  'Base del porcentaje': 'Monto sobre el que se calcula el porcentaje.',
  'Código de la otra regla': 'Regla cuyo monto sirve de base para este porcentaje.',
  'Cada cuántas': 'Cada cuántas unidades completas se suma el importe.',
  'Piso no baja de': 'Mínimo: el resultado nunca queda por debajo.',
  'Tope no pasa de': 'Máximo: el resultado nunca pasa de este valor.',
  'Qué significa el importe de cada tramo': 'Un importe fijo, una tarifa por unidad o una tarifa por tramo.',
  'De dónde sale el valor': 'Cómo se obtiene el importe: valor fijo, variable o tarifario.',
  'De qué tarifario sale el importe': 'Tabla de precios que se consulta.',
  'Qué valor de la fila usa': 'Columna de la fila del tarifario que se toma como importe.',
  'Clave': 'Variable con la que se busca la fila del tarifario.',
  'Clave del tarifario': 'Variables que identifican cada fila de la tabla.',
  'Agregar variable a la clave': 'Suma otra variable a la clave de búsqueda.',
  'Columnas de valor adicionales': 'Más columnas de precios además de la principal.',
  'Nombres de las columnas': 'Títulos de las columnas de valor, separados por coma.',
  'Cómo se cobra': 'Forma de cobrar: por kilómetro, por unidad, fijo u otra.',
  'Cómo se cobra cada fila': 'Cómo se interpreta el importe de cada fila de la hoja.',
  'Qué hacer con las filas que ya tiene la estructura': 'Reemplazarlas por las del archivo o conservarlas y agregar las nuevas.',
  'Qué hacer con las filas que ya tiene el tarifario': 'Reemplazarlas por las del archivo o conservarlas y agregar las nuevas.',
  'Decimales': 'Decimales con que se redondean los montos del país.',
  'Modo de redondeo': 'Cómo se redondean los centavos.',
  'Umbral de pernocta': 'Horas de viaje desde las que se cuenta una pernocta.',
  'Advertencia por debajo de': 'Margen bajo el cual la auditoría muestra una advertencia.',
  'Crítico por debajo de': 'Margen bajo el cual la auditoría queda en crítico.',
  'Días operativos por mes': 'Días que se trabajan al mes: divide los costos mensuales.',
  'Concepto': 'Nombre del gasto (por ejemplo, salario o llantas).',
  'Tipo': 'Clase de dato o de cobro.',
  'Frecuencia': 'Cada cuánto se paga o se repite este gasto.',
  'Hoja': 'Hoja del archivo de Excel que se va a leer.',
  'Fila de encabezado': 'Fila de la hoja donde están los títulos de las columnas.',
  'Fila del encabezado': 'Fila de la hoja donde están los títulos de las columnas.',
  'Formato de los números': 'Cómo están escritos los números en el archivo: 1.234,56 o 1,234.56.',
  'Motivo': 'Razón del cambio. Queda registrada en la bitácora.',
  'Motivo de la anulación': 'Por qué el pedido sale del reparto.',
  'Motivo de la re-liquidación': 'Por qué se vuelve a liquidar este viaje. Queda en la bitácora.',
  'Fecha': 'Fecha del viaje: decide qué reglas están vigentes.',
  'Desde': 'Fecha inicial del rango.',
  'Hasta': 'Fecha final del rango.',
  'Km': 'Kilómetros recorridos.',
  'Duración': 'Horas que duró el viaje.',
  'Paradas completadas': 'Paradas entregadas del viaje.',
  'Peso': 'Peso transportado en kilos.',
  'Volumen': 'Volumen de la carga en metros cúbicos.',
  'Capacidad': 'Capacidad del camión en toneladas.',
  'Tipo de camión': 'Clase de vehículo del viaje.',
  'Tipo de flota': 'Flota propia o externa.',
  'Flota': 'Flota propia o externa.',
  'Servicio': 'Clase de servicio: estándar, express o dedicado.',
  'Zona destino': 'Zona a la que llega el viaje.',
  'Zona origen': 'Zona de la que sale el viaje.',
  'Cliente': 'Identificador del cliente, para probar reglas que dependen de él.',
  'Escenario guardado': 'Viaje de prueba guardado para repetir el cálculo.',
  'Viaje completado': 'Marca el viaje como terminado.',
  'Unidad': 'Dato que se multiplica por la tarifa.',
  'Ayuda': 'Texto que explica el campo.',
  'Tipo de vista': 'Alterna entre vista simple y extendida.',
  'Ver desactivadas': 'Incluye en la lista las compañías desactivadas.',
};
