// Descripciones del tarifador: columnas de las tablas.

import type { HintMap } from '../../../components/base/hintKey';

export const COLUMNAS: HintMap = {
  'Avance': 'Cuántas paradas del viaje se completaron.',
  'Transportista': 'Compañía que hizo el viaje.',
  'Paradas': 'Paradas completadas sobre las planificadas.',
  'Nro': 'Número de la liquidación.',
  'Viaje': 'Número del viaje.',
  'Total': 'Monto total liquidado.',
  'Pedidos': 'Cantidad de pedidos del viaje.',
  'Pedido': 'Número del pedido.',
  'Guía': 'Guía de despacho del pedido.',
  'Estado': 'Situación actual.',
  'Acción': 'Qué se puede hacer con la fila.',
  'Cada cuánto': 'Cada cuánto se repite este gasto.',
  'Peso': 'Peso transportado en kilos.',
  'Acciones': 'Lo que se puede hacer con la fila.',
  'Entrega': 'Estado de entrega del pedido.',
  'Casa comercial': 'Cliente al que se le reparte el costo del viaje.',
  '%': 'Parte del total que le toca.',
  'Monto a pagar': 'Lo que le corresponde pagar a esa casa comercial.',
  'Valor de la mercancía': 'Valor de lo transportado.',
  'Proforma': 'Si la proforma está lista o pendiente.',
  'En la liquidación': 'Si el pedido entra o no en el reparto.',
  'Ganancia': 'Valor de la mercancía menos lo pagado; solo informativo.',
  'Prioridad': 'Orden de evaluación: menor número se evalúa primero.',
  'Competencia': 'Si la regla suma o compite con otras.',
  'Vigencia': 'Fechas entre las que la regla vale.',
  'Etapa': 'Momento del cálculo en que se aplica.',
  'Grupo': 'Grupo de reglas que compiten entre sí.',
  'Valores': 'Columnas de precio de la fila.',
  'Valor': 'Importe de la fila.',
  'Identificación fiscal': 'Cédula o RUT de la compañía.',
  'País Moneda': 'País y moneda en que se liquida.',
  'Cálculo': 'Si la compañía ya tiene su cálculo configurado.',
  'Componente': 'Gasto que forma parte del costo.',
  'Costo': 'Importe del gasto.',
  'Costo por km': 'Gasto expresado por kilómetro.',
  'Fijo mensual': 'Gasto fijo repartido por mes.',
  'Fijo diario': 'Gasto fijo repartido por día.',
  'Variable por km': 'Gasto que crece con los kilómetros.',
  'Combustible por km': 'Gasto de combustible por kilómetro.',
  'Tipo de camión ': 'Clase de vehículo a la que aplica.',
  'Unidades': 'Cantidad con la que se multiplica.',
  'Antes Después': 'Valor antes y después del cambio.',
  'Entidad': 'Qué se cambió: regla, tarifario, liquidación…',
  'Usuario': 'Quién hizo el cambio.',
  'Rol': 'Rol de quien hizo el cambio.',
  'Conductor': 'Persona que condujo el viaje.',
  'Vehículo': 'Placa y tipo del camión.',
};
