/* =====================================================================
   DDL de referencia — WMS/EFLOW (EFLOW_OLO)
   ---------------------------------------------------------------------
   Fuente: esquema real del WMS (SQL Server), solo ESTRUCTURA (sin datos).
   Motor: Microsoft SQL Server (dbo).
   Capturado: 2026-10-01.
   Propósito: insumo para los contratos de la rebanada delgada del OMS
     - ColaCandidatos  (lectura de candidatos)
     - ReglaFecha (T-1) (fecha base FECHAEXPEDICIONPLANIFICADA)
     - AnalizadorObservaciones (texto libre de observaciones)
     - HandoffPedidosOMS (escritura 2: voltear situación en el WMS)

   Tablas incluidas:
     1. EXPEDICIONESCABECERA      — cabecera del pedido/expedición (fuente del T-1 y la Cola)
     2. EXPEDICIONESDETALLE       — líneas del pedido (detalle)
     3. ALMACENMOVIMIENTOS_CARCAM — movimientos (anti-join de "no procesados")

   NOTA: este archivo es documentación de referencia. NO contiene
   credenciales ni datos. El acceso en vivo a QA/producción se hace desde
   el pipeline con secretos en Secrets Manager/SSM, nunca aquí.

   ---------------------------------------------------------------------
   MAPEOS DE DOMINIO CONFIRMADOS (EXPEDICIONESCABECERA) — 2026-10-01
   ---------------------------------------------------------------------
   * TPEXES = ESTADO del pedido      (varchar(6), FK TIPOSINTEGRACION)
   * TPEXSI = SITUACION del pedido   (varchar(6), FK TIPOSINTEGRACION)
   * Códigos (6 chars): "DISP" = disponible ; "GENE" = generada.
       - Filtro de la Cola (ColaCandidatos): estado/situación = DISP.
       - Escritura 2 del Handoff (HandoffPedidosOMS): situación (TPEXSI) -> "GENE".
         El estado (TPEXES) PERMANECE en "DISP" (solo cambia la situación). [confirmado 2026-10-01]
   * FECHAEXPEDICIONPLANIFICADA es NOT NULL -> el fallback de ReglaFecha
     NO se dispara por NULL, sino por valor por defecto/centinela
     (caso "cliente no envía fecha, se llena por default").
   * PRIORIDAD int NOT NULL = campo numérico de prioridad que escribe el OMS.
   * PESOPEDIDO_TOTAL / CUBICAJEPEDIDO_TOTAL (float NULL) = peso/volumen
     disponibles en origen (informa OQ-8; el handoff puede cargarlos).
   * Clave de idempotencia = PK (IDALMACEN, IDCOMPANIA, IDSUCURSAL, IDEXPEDICION).
   ===================================================================== */

-- =====================================================================
-- 1. EFLOW_OLO.dbo.EXPEDICIONESCABECERA
-- =====================================================================

CREATE TABLE EFLOW_OLO.dbo.EXPEDICIONESCABECERA (
    IDALMACEN varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDCOMPANIA varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDSUCURSAL varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDEXPEDICION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    TPEXPE varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDCLIENTE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDCLIENTEPROPIETARIO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MUELLEEXPEDICION varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDUNIDADTRANSPORTE varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CLASIFICACION1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CLASIFICACION2 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CLASIFICACION3 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CLASIFICACION4 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FECHAEXPEDICION datetime NOT NULL,
    FECHAEXPEDICIONPLANIFICADA datetime NOT NULL,
    FECHAGENERACION datetime NULL,
    FECHACIERRE datetime NULL,
    FECHAPLANIFICADADESPACHO datetime NULL,
    MANIFIESTOFISCAL varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PRIORIDAD int NOT NULL,
    OBSERVACIONESEXPEDICION varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    OBSERVACIONESINTEGRACION varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TPEXES varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    TPEXSI varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDEXPEDICIONFUCION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TPDOCERP varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DOCDEST varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TIPOCARGA varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REF1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REF2 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REF3 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    EMERGENCIA varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    KITS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FECHACREACION datetime NULL,
    RUTA varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDALMACENDESTINO varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDUSUARIOCREADOR varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MEDIOTRANSPORTE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    METODOENVIO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    NOMBREPRIORIDAD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MAX_LINEAS_USUARIO int NULL,
    COSTO_TOTAL float NULL,
    PESOPEDIDO_TOTAL float NULL,
    CUBICAJEPEDIDO_TOTAL float NULL,
    DIRECCIONPEDIDO varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FACTURA varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DUA varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    NUMEROVIAJEWMH bigint NULL,
    KITSPROCESADO bit NULL,
    TPDECO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    KITSVERIFICADOS bit NULL,
    BAJADA varchar(3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ORDEN_PRODUCCION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CODIGOUSUARIOMODIFICACION varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FECHAMODIFICACION datetime NULL,
    DOCUMENTOERP varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT PK_EXPEDICIONESCABECERA PRIMARY KEY (IDALMACEN,IDCOMPANIA,IDSUCURSAL,IDEXPEDICION),
    CONSTRAINT FK_EXPEDICIONESCABECERA_ALMACENCOMPANIA FOREIGN KEY (IDALMACEN,IDCOMPANIA) REFERENCES EFLOW_OLO.dbo.ALMACENCOMPANIA(IDALMACEN,IDCOMPANIA),
    CONSTRAINT FK_EXPEDICIONESCABECERA_CLIENTES FOREIGN KEY (IDCOMPANIA,IDCLIENTE) REFERENCES EFLOW_OLO.dbo.CLIENTES(IDCOMPANIA,IDCLIENTE),
    CONSTRAINT FK_EXPEDICIONESCABECERA_SUCURSAL FOREIGN KEY (IDCOMPANIA,IDSUCURSAL) REFERENCES EFLOW_OLO.dbo.SUCURSAL(IDCOMPANIA,IDSUCURSAL)
);
 CREATE NONCLUSTERED INDEX IX_EXPC_CARCAM_GRID_test ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , IDCOMPANIA ASC  , IDEXPEDICION ASC  )
     INCLUDE ( COSTO_TOTAL , IDCLIENTE , NUMEROVIAJEWMH ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDALMACEN_CLASIFICACION4_E0C34 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , CLASIFICACION4 ASC  ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDALMACEN_IDCOMPANIA_IDCLIENTE_3F0E9 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , IDCOMPANIA ASC  , IDCLIENTE ASC  )
     INCLUDE ( CLASIFICACION1 , CLASIFICACION2 , CLASIFICACION3 , CLASIFICACION4 , COSTO_TOTAL , DOCDEST , EMERGENCIA , FACTURA , FECHACIERRE , FECHACREACION , FECHAEXPEDICION , FECHAEXPEDICIONPLANIFICADA , FECHAGENERACION , FECHAPLANIFICADADESPACHO , IDALMACENDESTINO , IDEXPEDICIONFUCION , IDUNIDADTRANSPORTE , MANIFIESTOFISCAL , MAX_LINEAS_USUARIO , MEDIOTRANSPORTE , METODOENVIO , MUELLEEXPEDICION , NOMBREPRIORIDAD , OBSERVACIONESEXPEDICION , OBSERVACIONESINTEGRACION , PRIORIDAD , REF1 , REF2 , REF3 , RUTA , TIPOCARGA , TPDOCERP , TPEXES , TPEXPE , TPEXSI ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDALMACEN_IDCOMPANIA_IDUNIDADTRANSPORTE_TIPOCARGA_TPEXSI_NUMEROVIAJEWMH_2746F ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , IDCOMPANIA ASC  , IDUNIDADTRANSPORTE ASC  , TIPOCARGA ASC  , TPEXSI ASC  , NUMEROVIAJEWMH ASC  )
     INCLUDE ( FACTURA , PRIORIDAD , RUTA ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDALMACEN_IDEXPEDICION_TPEXSI_80D14 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , IDEXPEDICION ASC  , TPEXSI ASC  ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDALMACEN_TIPOCARGA_TPEXSI_673A9 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , TIPOCARGA ASC  , TPEXSI ASC  )
     INCLUDE ( FACTURA , FECHAEXPEDICION , IDCLIENTE , IDUNIDADTRANSPORTE , NUMEROVIAJEWMH , PRIORIDAD , RUTA , TPEXES ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDALMACEN_TPEXSI_2CD45 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , TPEXSI ASC  )
     INCLUDE ( EMERGENCIA , MAX_LINEAS_USUARIO , TPEXPE ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDCOMPANIA_TPEXPE_FECHACIERRE_TPEXSI_BC64B ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDCOMPANIA ASC  , TPEXPE ASC  , FECHACIERRE ASC  , TPEXSI ASC  ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDCOMPANIA_TPEXSI_6DF9D ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDCOMPANIA ASC  , TPEXSI ASC  )
     INCLUDE ( CLASIFICACION4 , KITSVERIFICADOS ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDCOMPANIA_TPEXSI_A8F07 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDCOMPANIA ASC  , TPEXSI ASC  )
     INCLUDE ( CLASIFICACION4 , KITSVERIFICADOS , TPEXPE ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_IDEXPEDICION_TPEXSI_DFE55 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDEXPEDICION ASC  , TPEXSI ASC  )
     INCLUDE ( KITS , TPEXPE ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_NUMEROVIAJEWMH_A39D5 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  NUMEROVIAJEWMH ASC  ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESCABECERA_TPEXES_TPEXSI_59D1E ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  TPEXES ASC  , TPEXSI ASC  )
     INCLUDE ( COSTO_TOTAL ) ;
 CREATE NONCLUSTERED INDEX IX_FACTURA ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  FACTURA ASC  ) ;
 CREATE NONCLUSTERED INDEX IX_IDALMACEN_IDCOMPANIA_IDSUCURSAL_RUTA_TPEXPE ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , IDCOMPANIA ASC  , IDSUCURSAL ASC  , RUTA ASC  , TPEXPE ASC  ) ;
 CREATE NONCLUSTERED INDEX IX_IDALMACEN_IDCOMPANIA_IDSUCURSAL_TPEXPE_REF1 ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  IDALMACEN ASC  , IDCOMPANIA ASC  , IDSUCURSAL ASC  , TPEXPE ASC  , REF1 ASC  ) ;
 CREATE NONCLUSTERED INDEX IX_TPEXPE_TPEXSI ON EFLOW_OLO.dbo.EXPEDICIONESCABECERA (  TPEXPE ASC  , TPEXSI ASC  )
     INCLUDE ( KITS ) ;

-- =====================================================================
-- 2. EFLOW_OLO.dbo.EXPEDICIONESDETALLE
-- =====================================================================

CREATE TABLE EFLOW_OLO.dbo.EXPEDICIONESDETALLE (
    IDALMACEN varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDCOMPANIA varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDSUCURSAL varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDEXPEDICION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDEXPEDICIONLINEA int NOT NULL,
    IDARTICULO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDPRESENTACION varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    LOTEEXPECIFICO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    UNIDADESPEDIDAS int NOT NULL,
    UNIDADESPREPARADAS int NULL,
    UNIDADESPROBLEMAS int NULL,
    PESOPREPARADO float NULL,
    CUBICAJEPREPARADO float NULL,
    VALORPREPARADO float NULL,
    GUIAFISCAL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PREPARARMAS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    PORCENTAJEMAS int NULL,
    PREPARARMENOS varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    PORCENTAJEMENOS int NULL,
    TPEXES varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    TPEXSI varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDEXPEDICIONFUCIONLINEA int NULL,
    OBSERVACIONES varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    UNIDADESCARGADAS int NULL,
    UNIDADESCONFIRMADAS int NULL,
    UNIDADESAUDITADAS int NULL,
    IDZONAGENERACION varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    BONIFICADO bit NULL,
    LINEABONIFICADO int NULL,
    ACONDICIONAMIENTO bit NULL,
    DUA varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REF1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REF2 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REF3 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    COSTOUNITARIO float NULL,
    IDMOVIMIENTOFISCAL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MANEJA_DIAS_DESPACHO varchar(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDLINEAORIGINAL int NULL,
    COSTO_TOTAL float NULL,
    IDPALETEXPECIFICO varchar(13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONTENEDOR varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PESOPEDIDO float NULL,
    CUBICAJEPEDIDO float NULL,
    IDTARIMA varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FACTOR float NULL,
    IDPRESENTACIONPEDIDO varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FECHACADUCIDAD datetime NULL,
    UNIDADESANULADAS int NULL,
    INCIDENCIA_PICK varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    INCIDENCIA_PACK varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT PK_EXPEDICIONESDETALLE_1 PRIMARY KEY (IDALMACEN,IDCOMPANIA,IDSUCURSAL,IDEXPEDICION,IDEXPEDICIONLINEA),
    CONSTRAINT FK_EXPEDICIONESDETALLE_ARTICULOSGESTION FOREIGN KEY (IDCOMPANIA,IDARTICULO) REFERENCES EFLOW_OLO.dbo.ARTICULOSGESTION(IDCOMPANIA,IDARTICULO),
    CONSTRAINT FK_EXPEDICIONESDETALLE_EXPEDICIONESCABECERA FOREIGN KEY (IDALMACEN,IDCOMPANIA,IDSUCURSAL,IDEXPEDICION) REFERENCES EFLOW_OLO.dbo.EXPEDICIONESCABECERA(IDALMACEN,IDCOMPANIA,IDSUCURSAL,IDEXPEDICION),
    CONSTRAINT FK_EXPEDICIONESDETALLE_TIPOSINTEGRACION FOREIGN KEY (TPEXES) REFERENCES EFLOW_OLO.dbo.TIPOSINTEGRACION(IDTIPO),
    CONSTRAINT FK_EXPEDICIONESDETALLE_TIPOSINTEGRACION1 FOREIGN KEY (TPEXSI) REFERENCES EFLOW_OLO.dbo.TIPOSINTEGRACION(IDTIPO)
);
 CREATE NONCLUSTERED INDEX IX_EXDET_CARCAM_GRID_test ON EFLOW_OLO.dbo.EXPEDICIONESDETALLE (  IDALMACEN ASC  , IDCOMPANIA ASC  , IDEXPEDICION ASC  , IDARTICULO ASC  , IDEXPEDICIONLINEA ASC  )
     INCLUDE ( COSTOUNITARIO , UNIDADESPEDIDAS , UNIDADESPREPARADAS ) ;
 CREATE NONCLUSTERED INDEX IX_EXPDET_COMPANIA_ARTICULO ON EFLOW_OLO.dbo.EXPEDICIONESDETALLE (  IDCOMPANIA ASC  , IDARTICULO ASC  ) ;
 CREATE NONCLUSTERED INDEX IX_EXPEDICIONESDETALLE_IDEXPEDICION_34CF6 ON EFLOW_OLO.dbo.EXPEDICIONESDETALLE (  IDEXPEDICION ASC  ) ;
-- NOTA: CK_EXPEDICIONESDETALLE_CANTIDAD aparece con CHECK (null) en el origen (constraint sin predicado efectivo).

-- =====================================================================
-- 3. EFLOW_OLO.dbo.ALMACENMOVIMIENTOS_CARCAM
-- =====================================================================

CREATE TABLE EFLOW_OLO.dbo.ALMACENMOVIMIENTOS_CARCAM (
    IDMOVIMIENTO bigint IDENTITY(1,1) NOT NULL,
    NUMEROVIAJE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDRASTREO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDPROCESO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDSUBPROCESO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    TIPOMOVIMIENTO varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDCODIGOACCION int NULL,
    TPTRAB varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    FECHAGENERACION datetime NULL,
    FECHAATENCION datetime NULL,
    FECHACIERRE datetime NULL,
    IDALMACEN varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDCOMPANIA varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDSUCURSAL varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    IDZONAALMACENAJE varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDZONAPICKING varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDZONATRABAJORECURSOS varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDZONATRABAJOPREPARACION varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDZONACOLAPREPARACION varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDALMACENAMIENTO int NULL,
    IDALMACENAMIENTOREFERENCIA varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDUBICACION varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDCONTENEDOR varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDRECURSO varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDUSUARIO varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDCLIENTE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDCLIENTEPROPIETARIO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDPROVEEDOR varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDARTICULO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDPRESENTACION varchar(4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    LOTE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDRECEPCION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDRECEPCIONLINEA int NULL,
    IDEXPEDICION varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDEXPEDICIONLINEA int NULL,
    IDSERIE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CANTIDAD float NULL,
    PESO float NULL,
    CUBICAJE float NULL,
    VALOR float NULL,
    COSTOMOVIMIENTO float NULL,
    DURACION float NULL,
    IDUNIDADTRANSPORTE varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDRUTADISTRIBUCION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    OBSERVACIONES varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ESTADO varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    SITUACION varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TURNO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDCHOFER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FECHACADUCIDAD datetime NULL,
    REF1 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REF2 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    REF3 varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDPRESENTACIONTRANSACCION varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FACTORTRANSACCION int NULL,
    IP varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MARCHAMO varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDCONFIRMACION varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DUA varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONTENEDOR varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IDMOVIMIENTOFISCAL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PLACA varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PAISPROCEDENCIA varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    NI int NULL,
    IDTOMAFISICA varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MOTIVO varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FECHAINICIO datetime NULL,
    ESTADO_FACTURACION varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MARCHAMO2 varchar(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DUA_INTERNAMIENTO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DUA_NACIONALIZADO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DUA_DESPACHO varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    USUARIO_APROBACION varchar(8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    NUMEROPARTE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MOVINVENTARIO varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    GUIAFISCAL varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FACTURA varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TEMPERATURA float NULL,
    CONSTRAINT PK_ALMACENMOVIMIENTOS_CARCAM PRIMARY KEY (IDMOVIMIENTO)
);
 CREATE NONCLUSTERED INDEX IX_ALMACENMOVIMIENTOS_CARCAM_IDALMACEN_IDCOMPANIA_IDSUCURSAL_IDEXPEDICION_CFB74 ON EFLOW_OLO.dbo.ALMACENMOVIMIENTOS_CARCAM (  IDALMACEN ASC  , IDCOMPANIA ASC  , IDSUCURSAL ASC  , IDEXPEDICION ASC  )
     INCLUDE ( CANTIDAD ) ;
 CREATE NONCLUSTERED INDEX IX_ALMACENMOVIMIENTOS_CARCAM_IDCOMPANIA_BED9F ON EFLOW_OLO.dbo.ALMACENMOVIMIENTOS_CARCAM (  IDCOMPANIA ASC  )
     INCLUDE ( IDALMACEN , NUMEROVIAJE ) ;
 CREATE NONCLUSTERED INDEX IX_ALMACENMOVIMIENTOS_CARCAM_NUMEROVIAJE_BCBF8 ON EFLOW_OLO.dbo.ALMACENMOVIMIENTOS_CARCAM (  NUMEROVIAJE ASC  )
     INCLUDE ( CANTIDAD , FECHACIERRE , FECHAGENERACION , IDALMACEN , IDARTICULO , IDCOMPANIA , IDCONFIRMACION , IDEXPEDICION , IDEXPEDICIONLINEA , IDSUCURSAL , IDUNIDADTRANSPORTE , PESO , PLACA ) ;
 CREATE NONCLUSTERED INDEX IX_NUMEROVIAJE_IDCOMPANIA ON EFLOW_OLO.dbo.ALMACENMOVIMIENTOS_CARCAM (  NUMEROVIAJE ASC  , IDCOMPANIA ASC  )
     INCLUDE ( IDALMACEN , IDARTICULO , IDCONTENEDOR , IDEXPEDICION , IDEXPEDICIONLINEA , IDSUCURSAL , IDUSUARIO ) ;

-- (Se omiten algunos índices adicionales de tuning de ALMACENMOVIMIENTOS_CARCAM
--  por no ser relevantes al contrato del OMS; la estructura de columnas y la PK
--  son las de arriba. El anti-join de "no procesados" usa las llaves
--  IDALMACEN + IDCOMPANIA + IDSUCURSAL + IDEXPEDICION.)
