version = 0.1
# Deploy (solo Intelix): sam build && sam deploy --config-env <dev|qa|prod>

[dev.deploy.parameters]
stack_name = "dev-tms-secrets"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
parameter_overrides = [
  "Environment=dev"
]
tags = ["Project=TMS", "Environment=DEV", "Name=dev-tms-secrets"]

[qa.deploy.parameters]
stack_name = "qa-tms-secrets"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
parameter_overrides = [
  "Environment=qa"
]
tags = ["Project=TMS", "Environment=QA", "Name=qa-tms-secrets"]

[prod.deploy.parameters]
stack_name = "prod-tms-secrets"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
parameter_overrides = [
  "Environment=prod"
]
tags = ["Project=TMS", "Environment=PROD", "Name=prod-tms-secrets"]
